version: "3.5"

services:
  apache-php:
    image: php:8.2-apache
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      replicas: 1
    depends_on:
      - mysql
    networks:
      - backend
      - host
    expose:
      - "8089:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
  mysql:
    image: mysql
    secrets:
      - db_root_password
      - db_dba_password
    deploy:
      replicas: 1
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_PASSWORD: /run/secrets/db_dba_password
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /opt/docker/volumes/mysql
        target: /var/lib/mysql

secrets:
  db_root_password:
    external: true
  db_dba_password:
    external: true

networks:
  backend:
  host:
    name: host
    external: true

    
    
    
volumes:
    data: