services:
  apache-php:
    build:
      context: './php'
      args:
        APACHE_VERSION:
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${PORT}:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    env_file: .env
    container_name: apache
    restart: unless-stopped
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
            - ${DB_DATA}:/var/lib/mysql
            - ${DB_INIT}/:/docker-entrypoint-initdb.d
    networks:
      - backend
    env_file: .env
    container_name: mysql
networks:
  frontend:
  backend:
volumes:
    data: